name: Build and Release
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
      - name: Creating local properties file
        run: echo signing.keyId=${{ secrets.SIGNING_KEYID }} >> local.properties
      - run: echo signing.password=${{ secrets.SIGNING_PASSWORD }} >> local.properties
      - run: echo ossrhUsername=${{ secrets.OSSRH_USERNAME }} >> local.properties 
      - run: echo ossrhPassword=${{ secrets.OSSRH_PASSWORD }} >> local.properties 
      - run: echo signing.secretKeyRingFile=key.gpg >> local.properties         
      - name: Creating key.gpg
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: 'd:\a\Unofficial-Spotify-SDK\Unofficial-Spotify-SDK\key.gpg'
          encodedString: ${{ secrets.SIGNING_KEY_GPG }}
      - run: dir
     # - run: chmod +x gradlew
      #- name: Build Gradle
       # run: ./gradlew build
        
